# Generated by Django 3.2.7 on 2021-10-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=65)),
                ('temp', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'City',
            },
        ),
    ]
