# Generated by Django 3.2.7 on 2021-10-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_weathermodels_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathermodels',
            name='icon',
        ),
    ]
