# Generated by Django 3.2.7 on 2021-10-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_weathermodels_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathermodels',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
