# Generated by Django 3.2.7 on 2021-10-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_weathermodels_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathermodels',
            name='city',
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
